version: '2'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=stackup_postgress
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    mongo:
        image: mongo
        restart: always
        ports:
          - "27017:27017"

volumes:
  postgres_data: